service: fileit
frameworkVersion: "3.17.0"
useDotenv: true

params: ${file(./environment/params.yml)}

provider: ${file(./environment/provider.yml)}

plugins:
  - serverless-offline
  - serverless-prune-plugin

custom:
  serverless-offline:
    host: 127.0.0.1
    httpPort: 4000
  prune:
    automatic: true
    number: 3

package:
  individually: true
  exclude:
    - ./.git/**
    - ./.serverless/**
    - ./node_modules/**
    - ./pkg/**
    - ./bootstrap/**
    - ./cmd/**
    - ./.dockers/**
    - ./.githooks/**
    - ./bin/**

functions:
  client-getall:
    description: Get all clients
    handler: bin/client-getall
    events:
      - httpApi:
          path: /clients
          method: get
          cors: true
    package:
      include:
        - ./bin/client-getall

  client-create:
    description: Create a client
    handler: bin/client-create
    events:
      - httpApi:
          path: /clients
          method: post
          cors: true
    package:
      include:
        - ./bin/client-create

  client-regen:
    description: Regen clients keys
    handler: bin/client-regen
    events:
      - httpApi:
          path: /clients/{id}/regen
          method: post
          cors: true
    package:
      include:
        - ./bin/client-regen
